### PR TITLE
Pyproject

### PR DESCRIPTION
**Pull request by cthulahoops**
* Adding `pyproject.toml` so `poetry install` lets me just run `aipl` without having to mess with paths.
* Fixing up argument parsing so that works.
* Using argparse so we get help.

### CODE REVIEW

**Comment by saulpw** [comment]
Thanks, @cthulahoops !  Should I remove requirements.txt or maintain both it and pyproject.toml separately?

**Comment by cthulahoops** [comment]
I'm not sure what the best practice is there. I have both in chatcli because I didn't want to make everyone install poetry, but I don't really maintain requirements.txt.

I also want to remove bin/aipl, but I thought I'd do that separately later.

**Comment by anjakefala** [comment]
I would really prefer we keep the `requirements.txt` in the repo! I have had issues with mixing `poetry` in my `conda` environments before. Maybe there is a way we can automatically update one from the other.

**Comment by cthulahoops** [comment]
Looks like this does something reasonable:

```
poetry export --without-hashes --format=requirements.txt > requirements.txt
```

**Comment by anjakefala** [comment]
@cthulahoops Great, I will add that to the CI!

**Pull request merged**
