### PR TITLE
Experiment with writing a grammar and parser.

### PR DESCRIPTION
**Pull request by cthulahoops**
Only the beginnings, creating a PR to share what I'm thinking about.

### CODE REVIEW

**Comment by saulpw** [comment]
Sweet!  I didn't know about Lark.  Will this handle multiple commands on a single line?

**Comment by cthulahoops** [comment]
> Sweet! I didn't know about Lark. Will this handle multiple commands on a single line?

It does now. (I keep forgetting that's allowed.)

It's my first time trying Lark. It took me a while to get my head around it (docs could be better), but it's working well now. It should let us improve the syntax a lot.

I'll be happy when we can allow this:

```
!split sep=' '
```

**Comment by cthulahoops** [comment]
This now passes all tests!

**Review by saulpw — APPROVED** [review]
Thanks @cthulahoops.  On the way to being a real language :)

**Pull request merged**
